name: Auto Deploy CI3 to VPS

on:
  push:
    branches:
      - master # Triggers on push to master

jobs:
  deploy:
    # Menggunakan label yang lebih spesifik agar tidak Queued lama
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync Files to VPS
        run: |
          # rsync akan mensinkronkan file lokal ke folder VPS
          # Menghindari overwrite config database dan folder log/cache
          rsync -avz --exclude '.git*' \
                    --exclude '.github' \
                    --exclude 'application/config/database.php' \
                    --exclude 'application/logs/*' \
                    --exclude 'application/cache/*' \
                    --delete \
                    . /var/www/iloveemas/

      - name: Fix Permissions
        run: |
          # Pastikan user 'ile_stg' memiliki izin di folder ini agar chmod berhasil
          chmod -R 777 /var/www/iloveemas/application/logs
          chmod -R 777 /var/www/iloveemas/application/cache
          echo "Deployment CI3 Selesai!"
